### ISSUE TITLE
Pubs: when possible add link to PDF

### ISSUE THREAD

**Issue by cmaumet** [NISOx-BDI/NISOx-BDI.github.io#10]
We should check the publication page for any missing PDF link, e.g. this one:
 - **Power and sample size calculations for fMRI studies based on the prevalence of active peaks.** Joke Durnez, Jasper Degryse, Beatrijs Moerkerke, Ruth Seurinck, Vanessa Sochat, Russell A Poldrack, and Thomas E Nichols. Technical Report .

is available at https://doi.org/10.1101/049429

**Comment by TomMaullin** [comment]
This has been addressed in PR #15
