### ISSUE TITLE
Presentations bibTex

### ISSUE THREAD

**Issue by TomMaullin** [NISOx-BDI/NISOx-BDI.github.io#19]
It would probably be good to eventually change the presentations data from YAML to bibtex so that we can put the correct umlauts and such on people's names. As this isn't necessary for the website to go live currently, it is a low priority. However, I do plan on changing this at some point.

**Comment by nicholst** [comment]
So you mean YAML can't deail with umlats etc?  I thought that wasn't a
problem - e.g.
https://stackoverflow.com/questions/488694/how-to-set-the-character-encoding-in-a-yaml-file

**Comment by TomMaullin** [comment]
Ah okay well currently the python scripts don't treat the YAML input as a unicode string but this can be easily rectified.

The other benefit to having the BibTeX over the YAML which I should have said before is that with the BibTeX you could just copy citations straight from figshare as oppose to having to write out each one as a YAML entry.

**Comment by nicholst** [comment]
> The other benefit to having the BibTeX over the YAML which I should have said before is that with the BibTeX you could just copy citations straight from figshare as oppose to having to write out each one as a YAML entry
> 
Oh! that is nice.  So, yes, let’s go with the BibTex approach.

**Comment by TomMaullin** [comment]
This has now been resolved in PR #21
