### ISSUE TITLE
URL reference for SnPM leads to 404 page

### ISSUE THREAD

**Issue by cmaumet** [NISOx-BDI/NISOx-BDI.github.io#44]
Hi @nicholst, @TomMaullin.

I was looking for the new official URL for SnPM. On the [SnPM page](http://www.nisox.org/Software/SnPM13/) (Nisox.org > Software > SnPM) it says:
```
URL reference: http://nisox.org/Software/SnPM
```

But  http://nisox.org/Software/SnPM currently leads to a 404 (not found) page.

**Comment by TomMaullin** [comment]
Ah sorry yes, I'll change this. It is currently at:

http://www.nisox.org/Software/SnPM13/

Cheers,
Tom M

**Comment by TomMaullin** [comment]
This is now sorted.

Cheers,
Tom M

**Comment by cmaumet** [comment]
Thanks! Here is an open question: do we also want to have a URL that will be common to all versions of SnPM? E.g. previously we had https://warwick.ac.uk/snpm. 

Maybe we could consider using [Zenodo](https://zenodo.org/) to create (and preserve) those identifiers for us? Zenodo would provide an identifier/URL for each SnPM versions AND a versionless identifier for the SnPM software. This would also allow to have different author lists for different versions. 

That's what they have in place for nipype: 
 - nypipe software (pointing to latest version): [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.596855.svg)](https://doi.org/10.5281/zenodo.596855) 
 -  nipype 0.13.1 [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.581704.svg)](https://doi.org/10.5281/zenodo.581704)

cf. http://blog.chrisgorgolewski.org/2017/11/sharing-academic-credit-in-open-source.html

(Zenodo and GitHub work well together: https://guides.github.com/activities/citable-code/).

**Comment by nicholst** [comment]
Wow!  Yes, this seems like a brilliant idea!  Is this something you can help me with?

On the author list, I guess it should be the union of everyone who has contributed to the project?  That looks like

Maumet, Camille
Thomas, Emma
Ding, Jun
Hayasaka, Satoru
Gitelman, Darren R
Holmes, Andrew P.
Nichols, Thomas E.

Where, mimicking the NiPype list I've arranged author order like on a paper.  Given how much you've been essentially managing it of late I think it's right that you're first.

No rush, of course...

**Comment by nicholst** [comment]
I've created an [issue](https://github.com/SnPM-toolbox/SnPM-devel/issues/58) on the SnPM site for this suggestion and we can close this as a website issue.

**Comment by cmaumet** [comment]
Thank you! Sorry for not replying earlier, I am happy to do take care of that!
