### ISSUE TITLE
Blog links point back to Warwick

### ISSUE THREAD

**Issue by nicholst** [NISOx-BDI/NISOx-BDI.github.io#49]
I was just visiting the blog https://blog.nisox.org/ and the last post is shown, "ERRATA FOR CLUSTER FAILURE", which is happy as that was the post I was looking for, actually the link-back: 

> Follow-up to [Bibliometrics of Cluster Inference](http://blogs.warwick.ac.uk/nichols/entry/bibliometrics_of_cluster/) from [Neuroimaging Statistics Tips & Tools](http://blogs.warwick.ac.uk/nichols/)

however, these link back are to http://blogs.warwick.ac.uk/nichols !  They need to go to the current blog.

@TomMaullin please revise links to http://blogs.warwick.ac.uk/nichols to point to the current blog; if it's not possible to create a script to do it, then at least manually do the posts from 2017.  Discuss with me what to do with the remaining Warwick-directed links.

**Comment by TomMaullin** [comment]
Ah sorry about this! I originally did this manually when moving over the blog posts and had missed a few links in the latest posts. You should now find that all blog links dating back to the start of the blog should work.

**Comment by nicholst** [comment]
Thanks @TomMaullin.  Looks good!
