### ISSUE TITLE
Pubs: there is currently a duplicate entry

### ISSUE THREAD

**Issue by cmaumet** [NISOx-BDI/NISOx-BDI.github.io#5]
<img width="741" alt="screen shot 2017-07-17 at 16 20 55" src="https://user-images.githubusercontent.com/5374264/28275512-f0f78596-6b0b-11e7-8d8e-b2553a05422b.png">

This needs to be further investigated.

**Comment by TomMaullin** [comment]
This has been addressed in PR #15
