### ISSUE TITLE
Software access URLs broken

### ISSUE THREAD

**Issue by nicholst** [NISOx-BDI/NISOx-BDI.github.io#53]
When I tried walking through the user registration for the NINGA software, after completing the Google form I was given an link that was 404!

Browsing the website, I see the problem is captialisation...  the form pointed me to: http://www.nisox.org/files/tars/ninga.zip when it appears it should be http://www.nisox.org/files/Tars/ninga.zip

@TomMaullin Can you fix this and check *all* of the software to ensure their links work?

**Comment by TomMaullin** [comment]
Apologies, this must have escaped one of the updates regarding case-sensitivity. It has now been resolved and all download links have been updated.
