### ISSUE TITLE
FSL logo is empty

### ISSUE THREAD

**Issue by cmaumet** [NISOx-BDI/NISOx-BDI.github.io#55]
at http://www.nisox.org/Software/

![screen shot 2018-03-05 at 17 06 03](https://user-images.githubusercontent.com/5374264/36985416-82331e4e-2097-11e8-8aac-73f6f67cbcdc.png)

**Comment by TomMaullin** [comment]
This is strange as it appears on mine. Is this the only image that does not appear in your browser?

**Comment by nicholst** [comment]
Agree, it appears on mine too.

**Comment by cmaumet** [comment]
Looking more closely this only happens on Firefox (Chrome and Safari are fine)...

**Comment by nicholst** [comment]
For what it's worth, it just work for me on my Firefox.

**Comment by cmaumet** [comment]
Okay... If you can't reproduce the issue, feel free to close this one :)

For the record here is the version I am using:

![screen shot 2018-03-08 at 08 45 23](https://user-images.githubusercontent.com/5374264/37139147-1a21f182-22ad-11e8-974a-c9926623a152.png)

**Comment by cmaumet** [comment]
Sorry!! I've just found out that it's the [privacy badger](https://www.eff.org/privacybadger) that was blocking the FSL images...
