### ISSUE TITLE
SwE Demo updates

### ISSUE THREAD

**Issue by nicholst** [NISOx-BDI/NISOx-BDI.github.io#58]
* Change Small Sample Adjustment & DF type... indicating that users can leave them at their defaults.

> Based on extensive simulations in Guillaume et al. [ref] and Guillaume [THESIS], we recommend leaving the Small sample adjustments and Degrees of freedom type to their default values, "type C2" and "approx III" respectively.  (The "approx II" Degrees of freedom type may be better than "approx III" but is only safe if using a balanced design).

**Comment by TomMaullin** [comment]
This has now been updated as requested.
