### ISSUE TITLE
Migrate: Presentations & posters from conferences

### ISSUE THREAD

**Issue by cmaumet** [NISOx-BDI/NISOx-BDI.github.io#6]
We will need to migrate slides & posters from invited talks and participation to conferences, currently available at: http://www2.warwick.ac.uk/fac/sci/statistics/staff/academic-research/nichols/presentations/.

To make those materials even more accessible, I would suggest hosting them on a public platform such as [figshare](https://figshare.com/), [F1000 research](https://f1000research.com/f1000posters-message), or even better our institutional platform [ORA](https://ora.ox.ac.uk/) and link from the website. This would also help to stay within GitHub storage limit (1GB per repository I think).

**Comment by nicholst** [comment]
Good point… I wasn’t thinking about repo size limits.

I see lots of people using figshare.  Do others have opinions on figshare vs F1000 vs other options?

**Comment by cmaumet** [comment]
@nicholst: Here are my two cents... For my personal website I currently use both slideshare and figshare:
 - I like [figshare](https://figshare.com/) for the doi and the easy PDF download 
 - and [slideshare](https://www.slideshare.net/) because you can get a png image of the first slide which makes it easy to create a gallery.

That being said, in the future I think that I will switch to use an institutional repository (like [ORA](https://ora.ox.ac.uk/)) because they are likely to provide more long-term persistency and I like the affiliation with the institution.

So far, I have never used  [F1000 research](https://f1000research.com/f1000posters-message).

Happy to hear more opinions!
