### ISSUE TITLE
Pubs: link to green open access PDFs?

### ISSUE THREAD

**Issue by cmaumet** [NISOx-BDI/NISOx-BDI.github.io#8]
When a publication is not open access on the publisher's website and when archive of post-print is allowed, could we share those post-prints and link to them from the "publications" page? 

Publisher copyright policies & self-archiving can be checked at: http://www.sherpa.ac.uk/romeo/

**Comment by nicholst** [comment]
Yes, good idea!

**Comment by cmaumet** [comment]
Great! So, I guess the institutional repositories ([WRAP](http://wrap.warwick.ac.uk), [ORA](https://ora.ox.ac.uk/)) would be the place to upload the post-prints and then link to there form the publication page? Or did you have another location in mind?

**Comment by nicholst** [comment]
Yes, WRAP/ORA is the default.  But if we've additionally used biorxiv and arxiv, is it easy to link to those too?  OR, I guess we could keep those as separate citations as 'pre prints'?

**Comment by cmaumet** [comment]
Yes, I would vote to update the biorxiv/arxiv version when they are available, to avoid having multiple copies of the same paper.

**Comment by nicholst** [comment]
Decided:  Have URL be the open access link, pubmed by default, and doi: also be included to offer canonical version (perhaps behind a paywall).

Find Pubmed url: https://www.ncbi.nlm.nih.gov/pubmed

**Comment by TomMaullin** [comment]
This has been addressed in PR #15
