### ISSUE TITLE
Blog: add commenting system

### ISSUE THREAD

**Issue by cmaumet** [NISOx-BDI/NISOx-BDI.github.io#9]
Possible options include:
 - [disqus](https://disqus.com) (cf. [this blog]( http://www.perfectlyrandom.org/2014/06/29/adding-disqus-to-your-jekyll-powered-github-pages/) for how to install on Jekyll powered by Github-Pages).

**Comment by nicholst** [comment]
Before we commit to yet another system that we would have to maintain/interface too, we should also see how it will be to interface with Wordpress. 

E.g. how well can a post be referenced/embeded from Wordpress.  Here's an example [COBIDAS: Data Sharing](https://cobidas.wordpress.com/2015/10/19/cobidas-data-sharing/).

**Comment by cmaumet** [comment]
We surely can! Though it will depend on what you decide in terms of hosting for the blog.

**Comment by TomMaullin** [comment]
This has been addressed by creating a wordpress blog.
